name: "Actualizar Últimos Videos de YouTube"

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-youtube-videos:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout el repositorio
        uses: actions/checkout@v4

      - name: Actualizar README con los últimos videos de YouTube
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UC-l_8ggAw-u4dJZtO05F5zQ"
          comment_tag_name: "YOUTUBE"
          template: "- [$title]($url)\n"
          max_post_count: "5"
