name: "Actualizar Últimos Videos de YouTube"

on:
  # Ejecuta este flujo de trabajo cada 12 horas
  schedule:
    - cron: '0 */12 * * *' # Cada 12 horas
  # Permite ejecutarlo manualmente desde la pestaña de Acciones
  workflow_dispatch:

jobs:
  update-youtube-videos:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permite que la acción escriba en el repositorio (para actualizar el README)

    steps:
      - name: Checkout el repositorio
        uses: actions/checkout@v4

      - name: Actualizar README con los últimos videos de YouTube
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UC-l_8ggAw-u4dJZtO05F5zQ"
          comment_tag_name: "YOUTUBE"
          template: "- [$title]($url)"
          max_post_count: "5"
          image_thumbnail: "true"
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
