name: "Actualizar Últimos Videos de YouTube"
on:
  schedule:
    - cron: '0 0 */2 * *'
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: YouTube Cards
        uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: "UC-l_8ggAw-u4dJZtO05F5zQ"
          comment_tag_name: "YOUTUBE-CARDS"
          max_videos: 6
          background_color: "0d1117" # Color fondo para que parezca nativo al modo oscuro
          title_color: "ffffff"
          stats_color: "8b949e"
